// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function() {
  return this.html_handler = (function(_super) {
    __extends(html_handler, _super);

    function html_handler() {
      return html_handler.__super__.constructor.apply(this, arguments);
    }

    html_handler.prototype.el = ".html-wrapper";

    html_handler.prototype.initialize = function() {
      return this.$el.on("click", "a", this.link_handler);
    };

    html_handler.prototype.link_handler = function(e) {};

    html_handler.prototype.insert_markup = function(html) {
      return this.$el.html(html);
    };

    html_handler.prototype.remove_markup = function() {
      return this.$el.empty();
    };

    return html_handler;

  })(Backbone.View);
});
