// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["moo"], function(moo) {
  var moo_router;
  return moo_router = (function(_super) {
    __extends(moo_router, _super);

    function moo_router() {
      return moo_router.__super__.constructor.apply(this, arguments);
    }

    moo_router.prototype.routes = {
      "*other": "moo"
    };

    moo_router.prototype.moo = function(param) {
      if (App.Views.mainView == null) {
        App.Views.mainView = new moo;
        return App.Views.mainView.render(param);
      }
    };

    return moo_router;

  })(Backbone.Router);
});
