// Generated by CoffeeScript 1.9.1
describe("moo", function() {
  it("should load instance of text_handler class into the 'app' namespace", function() {
    return expect(app.text).toBeDefined();
  });
  it("should define moo_name from params", function() {
    return expect(moo_name).toEqual("Literary Worlds");
  });
  it("should define host_name from params", function() {
    return expect(host_name).toEqual("brn227.brown.wmich.edu");
  });
  it("should define sock_server from params", function() {
    return expect(sock_server).toEqual("127.0.0.1");
  });
  it("should define port from params", function() {
    return expect(port).toEqual("7777");
  });
  it("should define font from params", function() {
    return expect(font).toEqual("Courier New");
  });
  it("should define fontsize from params", function() {
    return expect(fontsize).toEqual("12");
  });
  return it("should define localecho from params", function() {
    return expect(localecho).toEqual("false");
  });
});
