// Generated by CoffeeScript 1.7.1
var test;

test = {};

beforeEach(function() {
  return test.text = new text_handler();
});

describe("text_handler", function() {
  it("should correctly parse URLs at the beginning of text blocks", function() {});
  it("should correctly parse URLs at the end of text blocks", function() {});
  it("should show an error message", function() {});
  return it("should show an disconnect message", function() {});
});
