// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function() {
  return this.settings_modal = (function(_super) {
    __extends(settings_modal, _super);

    function settings_modal() {
      this.cleanup = __bind(this.cleanup, this);
      this.cancel = __bind(this.cancel, this);
      this.apply = __bind(this.apply, this);
      this.initialize = __bind(this.initialize, this);
      return settings_modal.__super__.constructor.apply(this, arguments);
    }

    settings_modal.prototype.el = "#settings-modal";

    settings_modal.prototype.events = {
      "click #btn-cancel": "cancel",
      "click #btn-ok": "apply"
    };

    settings_modal.prototype.initialize = function(opts) {
      this.$okBtn = this.$el.find("#btn-ok");
      return $(document).on("keyup checkout", (function(_this) {
        return function(e) {
          if (e.keyCode === 13) {
            e.preventDefault();
            _this.apply();
          }
          if (e.keyCode === 27) {
            e.preventDefault();
            return _this.cancel();
          }
        };
      })(this));
    };

    settings_modal.prototype.render = function() {
      this.$el.modal("show");
      return this;
    };

    settings_modal.prototype.apply = function(e) {
      var font, font_size, length;
      console.log('ok:' + e);
      length = parseInt(this.$el.find(".line-buf")[0].value);
      if (length !== null) {
        App.Views.text_handler.set_line_buffer(length);
      }
      font = $(".font-select")[0].value;
      font_size = $(".font-size").val();
      console.log(font + ":" + font_size);
      $(".text-mode-ul").css({
        "font-family": font,
        "font-size": font_size
      });
      return this.cleanup();
    };

    settings_modal.prototype.cancel = function() {
      return this.cleanup();
    };

    settings_modal.prototype.cleanup = function() {
      $(document).off("keyup checkout");
      this.$el.off("click", "#btn-cancel");
      this.$el.off("click", "#btn-ok");
      return this.$el.modal("hide");
    };

    return settings_modal;

  })(Backbone.View);
});
